end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
    display_formula:
      metric:
        - Edit_dist
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      data_path: /data/zhangchaobin/workspace/playground/eval/omnidocbench/OmniDocBench_1.json
    prediction:
      data_path: /data/zhangchaobin/workspace/playground/eval/omnidocbench/results
    match_method: quick_match